import './globals.css';
import type { Metadata } from 'next';
import { Patua_One } from 'next/font/google';

const patua = Patua_One({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-patua'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${patua.variable}`}>
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  )
};
